spring.application.name=image-service
server.port=${PORT}

management.endpoints.web.exposure.include=health,info,prometheus

eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health

eureka.client.healthcheck.enabled=true
logging.level.root=DEBUG


spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true
eureka.instance.non-secure-port=${PORT}